### PR TITLE
fix doesn't work encode

### PR DESCRIPTION
**Pull request by faithandbrave**
`if not gen7(length)` is bad. The function doesn't work if `firstPart | secondPart == 0`.

### CODE REVIEW

**Comment by Theelx** [comment]
Thank you, I was wondering why it didn't work for everything!

**Comment by Theelx** [comment]
By the way, @faithandbrave, does the cython version work properly?

**Comment by faithandbrave** [comment]
I haven't tried that.

**Comment by Theelx** [comment]
All good, I tested it myself and apparently it was horribly broken. It should work properly and be significantly faster now!

**Pull request merged**
